import { Prisma } from '@prisma/client';
import { prisma } from '../../configs/database.config.js';
import { AppError } from '../../shared/errors/app-error.js';
import type { MembershipTierBody, MembershipTierPatch } from './membership-tier.schemas.js';
function snapshot(tier: { name: string; threshold: Prisma.Decimal; discountPercent: Prisma.Decimal; benefits: string; birthdayGiftDescription: string; rank: number; isActive: boolean }) { return { name: tier.name, threshold: tier.threshold.toFixed(2), discountPercent: tier.discountPercent.toFixed(2), benefits: tier.benefits, birthdayGiftDescription: tier.birthdayGiftDescription, rank: tier.rank, isActive: tier.isActive }; }
async function assertUnique(transaction: Prisma.TransactionClient, value: { threshold: Prisma.Decimal; rank: number; id?: string; isActive: boolean }) { const conflict = await transaction.membershipTier.findFirst({ where: { ...(value.id ? { id: { not: value.id } } : {}), OR: [{ rank: value.rank }, ...(value.isActive ? [{ threshold: value.threshold, isActive: true }] : [])] } }); if (conflict) throw new AppError(409, 'MEMBERSHIP_TIER_CONFLICT', 'Tier rank or active threshold is already in use'); }
export function list() { return prisma.membershipTier.findMany({ include: { versions: { orderBy: { version: 'desc' }, take: 1 } }, orderBy: { rank: 'asc' } }); }
export async function create(input: MembershipTierBody, actorId: string) { return prisma.$transaction(async (transaction) => { const data = { ...input, threshold: new Prisma.Decimal(input.threshold), discountPercent: new Prisma.Decimal(input.discountPercent), isActive: input.isActive ?? true }; await assertUnique(transaction, data); const tier = await transaction.membershipTier.create({ data }); const version = await transaction.membershipTierVersion.create({ data: { tierId: tier.id, version: 1, ...snapshot(tier) } }); await transaction.membershipTierAudit.create({ data: { tierId: tier.id, actorId, action: 'created', after: { ...snapshot(tier), versionId: version.id } } }); return tier; }); }
export async function update(id: string, input: MembershipTierPatch, actorId: string) { return prisma.$transaction(async (transaction) => { const current = await transaction.membershipTier.findUnique({ where: { id } }); if (!current) throw new AppError(404, 'MEMBERSHIP_TIER_NOT_FOUND', 'Membership tier not found'); const data: Prisma.MembershipTierUncheckedUpdateInput = { ...(input.name !== undefined ? { name: input.name } : {}), ...(input.threshold !== undefined ? { threshold: new Prisma.Decimal(input.threshold) } : {}), ...(input.discountPercent !== undefined ? { discountPercent: new Prisma.Decimal(input.discountPercent) } : {}), ...(input.benefits !== undefined ? { benefits: input.benefits } : {}), ...(input.birthdayGiftDescription !== undefined ? { birthdayGiftDescription: input.birthdayGiftDescription } : {}), ...(input.rank !== undefined ? { rank: input.rank } : {}), ...(input.isActive !== undefined ? { isActive: input.isActive } : {}) }; const candidate = { threshold: data.threshold instanceof Prisma.Decimal ? data.threshold : current.threshold, rank: typeof data.rank === 'number' ? data.rank : current.rank, isActive: typeof data.isActive === 'boolean' ? data.isActive : current.isActive, id }; await assertUnique(transaction, candidate); const tier = await transaction.membershipTier.update({ where: { id }, data }); const latest = await transaction.membershipTierVersion.aggregate({ where: { tierId: id }, _max: { version: true } }); const version = await transaction.membershipTierVersion.create({ data: { tierId: id, version: (latest._max.version ?? 0) + 1, ...snapshot(tier) } }); await transaction.membershipTierAudit.create({ data: { tierId: id, actorId, action: 'updated', before: snapshot(current), after: { ...snapshot(tier), versionId: version.id } } }); return tier; }); }
export async function history(id: string) { const tier = await prisma.membershipTier.findUnique({ where: { id }, include: { versions: { orderBy: { version: 'desc' } }, audits: { orderBy: { createdAt: 'desc' }, include: { actor: { select: { id: true, name: true, email: true } } } } } }); if (!tier) throw new AppError(404, 'MEMBERSHIP_TIER_NOT_FOUND', 'Membership tier not found'); return tier; }
