import { Prisma } from '@prisma/client';
import { prisma } from '../../configs/database.config.js';
import { adToBs, localDateParts, membershipYear } from '../calendar/calendar.service.js';
import { AppError } from '../errors/app-error.js';
import { paginatedResult } from '../http/pagination.js';
import type { BirthdayQuery, CustomerDirectoryQuery } from './directory.schemas.js';

const orderFor = (sort: CustomerDirectoryQuery['sort']) => ({ current_year_spend_desc: Prisma.sql`COALESCE(my."eligibleNetSpend", 0) DESC, cp."id" ASC`, current_year_spend_asc: Prisma.sql`COALESCE(my."eligibleNetSpend", 0) ASC, cp."id" ASC`, lifetime_spend_desc: Prisma.sql`COALESCE(life."total", 0) DESC, cp."id" ASC`, lifetime_spend_asc: Prisma.sql`COALESCE(life."total", 0) ASC, cp."id" ASC`, membership_rank_desc: Prisma.sql`COALESCE(tv."rank", -1) DESC, cp."id" ASC`, membership_rank_asc: Prisma.sql`COALESCE(tv."rank", 2147483647) ASC, cp."id" ASC`, name_asc: Prisma.sql`cp."fullName" ASC, cp."id" ASC`, name_desc: Prisma.sql`cp."fullName" DESC, cp."id" ASC` })[sort];
function conditions(query: CustomerDirectoryQuery) {
  const result: Prisma.Sql[] = [Prisma.sql`cp."state" = 'active'::"CustomerProfileState"`];
  if (query.search) { const value = `%${query.search.toLowerCase()}%`; result.push(Prisma.sql`(lower(cp."fullName") LIKE ${value} OR cp."normalizedPhone" LIKE ${value} OR cp."normalizedEmail" LIKE ${value})`); }
  if (query.membershipTierId) result.push(Prisma.sql`my."activeTierId" = ${query.membershipTierId}`);
  if (query.membershipStatus === 'none') result.push(Prisma.sql`my."activeTierId" IS NULL`);
  return Prisma.join(result, ' AND ');
}
export async function listCustomers(query: CustomerDirectoryQuery) {
  const year = membershipYear(); const where = conditions(query); const offset = (query.page - 1) * query.limit;
  const rows = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT cp."id", cp."fullName", cp."normalizedPhone", cp."normalizedEmail", cp."birthDate", cp."preferredCalendar", my."eligibleNetSpend", my."activatedAt", my."activeTierId", tv."name" AS "tierName", tv."rank" AS "tierRank", tv."discountPercent", COALESCE(life."total", 0) AS "lifetimeNetSpend" FROM "customer_profiles" cp LEFT JOIN "customer_membership_years" my ON my."customerProfileId" = cp."id" AND my."year" = ${year} LEFT JOIN "membership_tier_versions" tv ON tv."id" = my."activeTierVersionId" LEFT JOIN LATERAL (SELECT COALESCE(SUM("total"), 0) AS "total" FROM "pos_sales" WHERE "customerProfileId" = cp."id") ps ON true LEFT JOIN LATERAL (SELECT COALESCE(SUM("total"), 0) AS "total" FROM "orders" WHERE "customerProfileId" = cp."id" AND "paymentStatus" = 'paid'::"OrderPaymentStatus") ws ON true LEFT JOIN LATERAL (SELECT ps."total" + ws."total" AS "total") life ON true WHERE ${where} ORDER BY ${orderFor(query.sort)} LIMIT ${query.limit} OFFSET ${offset}`);
  const counts = await prisma.$queryRaw<Array<{ count: number }>>(Prisma.sql`SELECT COUNT(*)::int AS "count" FROM "customer_profiles" cp LEFT JOIN "customer_membership_years" my ON my."customerProfileId" = cp."id" AND my."year" = ${year} WHERE ${where}`);
  return paginatedResult(rows.map((row) => ({ ...row, eligibleNetSpend: new Prisma.Decimal(row.eligibleNetSpend ?? 0).toFixed(2), lifetimeNetSpend: new Prisma.Decimal(row.lifetimeNetSpend ?? 0).toFixed(2), discountPercent: row.discountPercent ? new Prisma.Decimal(row.discountPercent).toFixed(2) : '0.00' })), counts[0]?.count ?? 0, query);
}
export async function getCustomer(id: string) { const profile = await prisma.customerProfile.findUnique({ where: { id }, include: { membershipYears: { where: { year: membershipYear() }, include: { activeTierVersion: true } } } }); if (!profile) throw new AppError(404, 'CUSTOMER_NOT_FOUND', 'Customer not found'); return profile; }
export async function birthdays(query: BirthdayQuery) { const today = localDateParts(); const bsToday = adToBs(new Date(Date.UTC(today.year, today.month - 1, today.day))); const upcoming = query.mode === 'upcoming'; const match = upcoming ? Prisma.sql`(cp."preferredCalendar" = 'AD'::"PreferredCalendar" AND EXTRACT(MONTH FROM cp."birthDate")::int = ${today.month}) OR (cp."preferredCalendar" = 'BS'::"PreferredCalendar" AND cp."bsBirthMonth" = ${bsToday.month})` : Prisma.sql`(cp."preferredCalendar" = 'AD'::"PreferredCalendar" AND EXTRACT(MONTH FROM cp."birthDate")::int = ${today.month} AND EXTRACT(DAY FROM cp."birthDate")::int = ${today.day}) OR (cp."preferredCalendar" = 'BS'::"PreferredCalendar" AND cp."bsBirthMonth" = ${bsToday.month} AND cp."bsBirthDay" = ${bsToday.day})`; const rows = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT cp.* FROM "customer_profiles" cp WHERE cp."state" = 'active'::"CustomerProfileState" AND (${match}) ORDER BY cp."fullName" ASC, cp."id" ASC LIMIT ${query.limit} OFFSET ${(query.page - 1) * query.limit}`); const count = await prisma.$queryRaw<Array<{ count: number }>>(Prisma.sql`SELECT COUNT(*)::int AS "count" FROM "customer_profiles" cp WHERE cp."state" = 'active'::"CustomerProfileState" AND (${match})`); return paginatedResult(rows, count[0]?.count ?? 0, query); }
