import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { Queue, Worker, type JobsOptions } from 'bullmq';
import { Redis } from 'ioredis';
import { Resend } from 'resend';
import { EmailOutboxStatus, Prisma, type EmailKind } from '@prisma/client';
import { envVariables } from '../../configs/env.config.js';
import { logger } from '../../configs/logger.config.js';
import { prisma } from '../../configs/database.config.js';

type EmailPayload = { subject: string; html: string; text: string };
const queueName = 'rogueon-email-outbox';
const retryOptions: JobsOptions = { attempts: 5, backoff: { type: 'exponential', delay: 2_000 }, removeOnComplete: 1_000, removeOnFail: 2_000 };
let connection: Redis | undefined; let queue: Queue<{ outboxId: string }> | undefined;
function redisConnection() { if (!envVariables.REDIS_URL) return undefined; connection ??= new Redis(envVariables.REDIS_URL, { maxRetriesPerRequest: null }); return connection; }
function emailQueue() { const redis = redisConnection(); if (!redis) return undefined; queue ??= new Queue(queueName, { connection: redis }); return queue; }
function shouldDeliverEmail() { return envVariables.NODE_ENV === 'production' || envVariables.EMAIL_DELIVERY_MODE === 'resend'; }
function encryptionKey() { return envVariables.EMAIL_OUTBOX_ENCRYPTION_KEY ? createHash('sha256').update(envVariables.EMAIL_OUTBOX_ENCRYPTION_KEY).digest() : undefined; }
function encrypt(payload: EmailPayload) { const key = encryptionKey(); if (!key) throw new Error('EMAIL_OUTBOX_ENCRYPTION_KEY is required for auth emails'); const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', key, iv); const encrypted = Buffer.concat([cipher.update(JSON.stringify(payload), 'utf8'), cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${encrypted.toString('base64url')}`; }
function decrypt(value: string): EmailPayload { const key = encryptionKey(); if (!key) throw new Error('Email encryption key is unavailable'); const [ivValue, tagValue, bodyValue] = value.split('.'); if (!ivValue || !tagValue || !bodyValue) throw new Error('Invalid encrypted email payload'); const decipher = createDecipheriv('aes-256-gcm', key, Buffer.from(ivValue, 'base64url')); decipher.setAuthTag(Buffer.from(tagValue, 'base64url')); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(bodyValue, 'base64url')), decipher.final()]).toString('utf8')) as EmailPayload; }

export async function createEmailOutbox(input: { kind: EmailKind; recipientEmail: string; deduplicationKey: string; payload: EmailPayload; sensitive?: boolean; expiresAt?: Date }, transaction: Prisma.TransactionClient = prisma) {
  if (!shouldDeliverEmail()) logger.info('Development email (not sent)', { kind: input.kind, to: input.recipientEmail, subject: input.payload.subject, text: input.payload.text });
  const create = input.sensitive ? { kind: input.kind, recipientEmail: input.recipientEmail, deduplicationKey: input.deduplicationKey, encryptedPayload: encrypt(input.payload), ...(input.expiresAt ? { expiresAt: input.expiresAt } : {}) } : { kind: input.kind, recipientEmail: input.recipientEmail, deduplicationKey: input.deduplicationKey, payload: input.payload as Prisma.InputJsonValue, ...(input.expiresAt ? { expiresAt: input.expiresAt } : {}) };
  return transaction.emailOutbox.upsert({ where: { deduplicationKey: input.deduplicationKey }, create, update: {} });
}
export async function enqueueOutboxId(outboxId: string) { const target = emailQueue(); if (!target) return false; await target.add('deliver', { outboxId }, { ...retryOptions, jobId: `email-${outboxId}` }); await prisma.emailOutbox.updateMany({ where: { id: outboxId, status: EmailOutboxStatus.pending }, data: { status: EmailOutboxStatus.queued } }); return true; }
export async function enqueueAuthEmail(input: { to: string; subject: string; html: string; text: string; kind: EmailKind }) { if (!shouldDeliverEmail()) { logger.info('Development authentication email (not sent)', { kind: input.kind, to: input.to, subject: input.subject, text: input.text }); return; } if (!envVariables.RESEND_API_KEY || !envVariables.RESEND_FROM_EMAIL) { logger.warn('Authentication email skipped because Resend is not configured'); return; } const outbox = await createEmailOutbox({ ...input, recipientEmail: input.to, deduplicationKey: `${input.kind}:${createHash('sha256').update(input.text).digest('hex')}`, payload: { subject: input.subject, html: input.html, text: input.text }, sensitive: true, expiresAt: new Date(Date.now() + 3_600_000) }); void enqueueOutboxId(outbox.id).catch(() => logger.warn('Email outbox will be recovered by worker dispatcher')); }
function payloadFor(outbox: { payload: Prisma.JsonValue | null; encryptedPayload: string | null }) { if (outbox.encryptedPayload) return decrypt(outbox.encryptedPayload); if (!outbox.payload || typeof outbox.payload !== 'object' || Array.isArray(outbox.payload)) throw new Error('Invalid email outbox payload'); const { subject, html, text } = outbox.payload as EmailPayload; return { subject, html, text }; }
export async function deliverOutbox(outboxId: string) { const outbox = await prisma.emailOutbox.findUnique({ where: { id: outboxId } }); if (!outbox || outbox.status === EmailOutboxStatus.sent || outbox.status === EmailOutboxStatus.expired) return; if (outbox.expiresAt && outbox.expiresAt <= new Date()) { await prisma.emailOutbox.update({ where: { id: outbox.id }, data: { status: EmailOutboxStatus.expired, payload: Prisma.JsonNull, encryptedPayload: null } }); return; } const payload = payloadFor(outbox); if (!shouldDeliverEmail()) { logger.info('Development outbox email (not sent)', { kind: outbox.kind, to: outbox.recipientEmail, subject: payload.subject, text: payload.text }); await prisma.emailOutbox.update({ where: { id: outbox.id }, data: { status: EmailOutboxStatus.sent, sentAt: new Date(), payload: Prisma.JsonNull, encryptedPayload: null, lastErrorCode: null } }); return; } const resend = envVariables.RESEND_API_KEY && envVariables.RESEND_FROM_EMAIL ? new Resend(envVariables.RESEND_API_KEY) : undefined; if (!resend || !envVariables.RESEND_FROM_EMAIL) throw new Error('Resend is not configured'); await prisma.emailOutbox.update({ where: { id: outbox.id }, data: { status: EmailOutboxStatus.sending, attempts: { increment: 1 } } }); const result = await resend.emails.send({ from: envVariables.RESEND_FROM_EMAIL, to: outbox.recipientEmail, ...payload }); if (result.error) throw new Error(result.error.message); await prisma.emailOutbox.update({ where: { id: outbox.id }, data: { status: EmailOutboxStatus.sent, sentAt: new Date(), providerMessageId: result.data?.id ?? null, payload: Prisma.JsonNull, encryptedPayload: null, lastErrorCode: null } }); }
export async function dispatchPendingOutbox() { const pending = await prisma.emailOutbox.findMany({ where: { status: { in: [EmailOutboxStatus.pending, EmailOutboxStatus.queued] }, availableAt: { lte: new Date() } }, select: { id: true }, take: 100, orderBy: { createdAt: 'asc' } }); await Promise.all(pending.map((row) => enqueueOutboxId(row.id))); return pending.length; }
export function startEmailWorker() { const redis = redisConnection(); if (!redis) { logger.warn('Email worker disabled because REDIS_URL is not configured'); return undefined; } const worker = new Worker<{ outboxId: string }>(queueName, async (job) => deliverOutbox(job.data.outboxId), { connection: redis }); worker.on('error', (error) => logger.error('Email worker connection error', { error: error.message })); worker.on('failed', async (job, error) => { if (!job || job.attemptsMade < (job.opts.attempts ?? 1)) return; await prisma.emailOutbox.updateMany({ where: { id: job.data.outboxId, status: { not: EmailOutboxStatus.sent } }, data: { status: EmailOutboxStatus.failed, lastErrorCode: error.name, payload: Prisma.JsonNull, encryptedPayload: null } }); logger.error('Email delivery permanently failed', { outboxId: job.data.outboxId, error: error.message }); }); return worker; }
