import { Router } from 'express';
import { validateRequest } from '../../shared/validation/validation.middleware.js';
import { customerDirectoryQuerySchema, customerIdParamsSchema, birthdayQuerySchema } from '../../shared/customers/directory.schemas.js';
import { customerProfileInputSchema } from '../../shared/customers/customer.schemas.js';
import * as controller from './customer.controller.js';
export const posCustomerRouter = Router();
posCustomerRouter.get('/birthdays', validateRequest({ query: birthdayQuerySchema }), controller.birthdays);
posCustomerRouter.get('/', validateRequest({ query: customerDirectoryQuerySchema }), controller.list);
posCustomerRouter.post('/', validateRequest({ body: customerProfileInputSchema }), controller.create);
posCustomerRouter.get('/:id', validateRequest({ params: customerIdParamsSchema }), controller.getOne);
